# Generated by Django 5.2.4 on 2025-08-25 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0001_initial"),
        ("resort", "0005_resort_company"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipientGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Dai un nome a questo gruppo, es. 'Tutti i Manutentori'",
                        max_length=100,
                    ),
                ),
                (
                    "roles",
                    models.CharField(
                        blank=True,
                        help_text="Elenco di ruoli separati da virgola",
                        max_length=255,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipient_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resorts",
                    models.ManyToManyField(
                        blank=True, related_name="recipient_groups", to="resort.resort"
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="recipient_groups_member",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
