# Generated by Django 5.2.4 on 2025-08-28 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0003_announcement_read_by"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        ("resort", "0005_resort_company"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledEmailReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Un nome per questo report programmato, es. 'Report Giornaliero Direttori'",
                        max_length=200,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Disattiva per sospendere l'invio programmato di questo report.",
                        verbose_name="Attivo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "periodic_task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_celery_beat.periodictask",
                        verbose_name="Task Programmato",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        related_name="email_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinatari",
                    ),
                ),
                (
                    "resorts",
                    models.ManyToManyField(
                        help_text="Seleziona i resort da includere nel report.",
                        to="resort.resort",
                        verbose_name="Resort Inclusi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Email Programmato",
                "verbose_name_plural": "Report Email Programmati",
                "ordering": ["-created_at"],
            },
        ),
    ]
