# Generated by Django 5.2.4 on 2025-08-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0004_scheduledemailreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledemailreport",
            name="custom_end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data di Fine (personalizzata)"
            ),
        ),
        migrations.AddField(
            model_name="scheduledemailreport",
            name="custom_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data di Inizio (personalizzata)"
            ),
        ),
        migrations.AddField(
            model_name="scheduledemailreport",
            name="report_period",
            field=models.CharField(
                choices=[
                    ("daily", "Giorno Precedente"),
                    ("monthly", "Mese Precedente"),
                    ("custom", "Intervallo Personalizzato"),
                ],
                default="daily",
                max_length=20,
                verbose_name="Periodo del Report",
            ),
        ),
    ]
