# Generated by Django 5.2.4 on 2025-09-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0005_scheduledemailreport_custom_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledemailreport",
            name="day_of_week",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Lunedì"),
                    ("2", "Martedì"),
                    ("3", "Mercoledì"),
                    ("4", "Giovedì"),
                    ("5", "Venerdì"),
                    ("6", "Sabato"),
                    ("0", "Domenica"),
                ],
                default="1",
                max_length=1,
                verbose_name="Giorno della Settimana (se settimanale)",
            ),
        ),
        migrations.AddField(
            model_name="scheduledemailreport",
            name="frequency",
            field=models.CharField(
                choices=[("daily", "Ogni Giorno"), ("weekly", "Ogni Settimana")],
                default="daily",
                max_length=10,
                verbose_name="Frequenza di Invio",
            ),
        ),
        migrations.AddField(
            model_name="scheduledemailreport",
            name="hour",
            field=models.IntegerField(default=8, verbose_name="Ora di invio"),
        ),
        migrations.AddField(
            model_name="scheduledemailreport",
            name="minute",
            field=models.IntegerField(default=0, verbose_name="Minuto di invio"),
        ),
        migrations.AddField(
            model_name="scheduledemailreport",
            name="review_period_days",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Includi le recensioni degli ultimi X giorni.",
                verbose_name="Periodo Recensioni (giorni)",
            ),
        ),
        migrations.AlterField(
            model_name="scheduledemailreport",
            name="custom_end_date",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="scheduledemailreport",
            name="custom_start_date",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="scheduledemailreport",
            name="report_period",
            field=models.CharField(default="daily", editable=False, max_length=20),
        ),
    ]
