# Generated by Django 5.2.4 on 2025-11-26 08:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_booking_access_token_signature"),
        ("communications", "0006_scheduledemailreport_day_of_week_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=255)),
                ("recipient", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Successo"), ("failed", "Fallito")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("link_used", models.URLField(blank=True, null=True)),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                ("payload", models.JSONField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
