# Generated by Django 5.2.4 on 2025-10-22 15:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0003_company_logo"),
        ("purchase_orders", "0004_purchasecategory_alter_budget_options_and_more"),
        ("resort", "0006_seed_resorts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EconomatoCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Colore personalizzato per dashboard e tagging (es. 'primary', '#FF8800').",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Società proprietaria della categoria.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="economato_categories",
                        to="clients.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria Economato",
                "verbose_name_plural": "Categorie Economato",
                "ordering": ["name"],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.CreateModel(
            name="EconomatoCostCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="economato_cost_centers",
                        to="clients.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Centro di costo Economato",
                "verbose_name_plural": "Centri di costo Economato",
                "ordering": ["code"],
                "unique_together": {("company", "code")},
            },
        ),
        migrations.CreateModel(
            name="EconomatoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("pz", "Pezzi"),
                            ("kg", "Chilogrammi"),
                            ("lt", "Litri"),
                            ("box", "Box"),
                            ("set", "Set"),
                        ],
                        default="pz",
                        max_length=10,
                    ),
                ),
                (
                    "reorder_point",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Livello minimo di scorta prima del riordino.",
                    ),
                ),
                (
                    "optimal_stock",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Livello ottimale di scorta per l'articolo.",
                    ),
                ),
                (
                    "last_purchase_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="economato.economatocategory",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Società proprietaria dell'articolo.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="economato_items",
                        to="clients.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="economato_items_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resort",
                    models.ForeignKey(
                        blank=True,
                        help_text="Resort specifico a cui è dedicato l'articolo (opzionale).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="economato_items",
                        to="resort.resort",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="economato_items",
                        to="purchase_orders.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Articolo Economato",
                "verbose_name_plural": "Articoli Economato",
                "ordering": ["name"],
                "unique_together": {("company", "code")},
            },
        ),
        migrations.CreateModel(
            name="EconomatoRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Bozza"),
                            ("pending", "In Approvazione"),
                            ("approved", "Approvata"),
                            ("rejected", "Rifiutata"),
                            ("fulfilled", "Completata"),
                            ("cancelled", "Annullata"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Bassa"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                            ("critical", "Critica"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("needed_by", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "total_estimated_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="economato_requests_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="economato_requests",
                        to="clients.company",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requests",
                        to="economato.economatocostcenter",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="economato_requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="economato_requests",
                        to="resort.resort",
                    ),
                ),
            ],
            options={
                "verbose_name": "Richiesta Economato",
                "verbose_name_plural": "Richieste Economato",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EconomatoRequestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_of_measure", models.CharField(blank=True, max_length=20)),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="request_lines",
                        to="economato.economatoitem",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="economato.economatorequest",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="economato_request_items",
                        to="purchase_orders.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Articolo Richiesta Economato",
                "verbose_name_plural": "Articoli Richiesta Economato",
            },
        ),
        migrations.CreateModel(
            name="EconomatoTimelineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("verb", models.CharField(max_length=120)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="economato_timeline_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline",
                        to="economato.economatorequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento Timeline Economato",
                "verbose_name_plural": "Eventi Timeline Economato",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="EconomatoStockLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("reserved_quantity", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_levels",
                        to="economato.economatoitem",
                    ),
                ),
                (
                    "resort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="economato_stock_levels",
                        to="resort.resort",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="economato_stock_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Giacenza Economato",
                "verbose_name_plural": "Giacenze Economato",
                "unique_together": {("item", "resort")},
            },
        ),
    ]
