# Generated by Django 5.2.4 on 2025-09-15 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0003_company_logo"),
        ("resort", "0005_resort_company"),
        ("reviews", "0011_scheduledscraping"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nome Competitor"),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="Sito Web"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data di Creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data di Aggiornamento"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitors",
                        to="clients.company",
                        verbose_name="Società di appartenenza",
                    ),
                ),
            ],
            options={
                "verbose_name": "Competitor",
                "verbose_name_plural": "Competitors",
                "ordering": ["name"],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.CreateModel(
            name="ScrapingLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(max_length=1024, verbose_name="URL da Scansionare"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Attivo")),
                (
                    "platform_options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Es. {"max_reviews": 50}. Le opzioni verranno passate all\'attore Apify.',
                        verbose_name="Opzioni Piattaforma",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scraping_links",
                        to="competitors.competitor",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="competitor_scraping_links",
                        to="reviews.reviewsource",
                        verbose_name="Piattaforma di Scraping",
                    ),
                ),
            ],
            options={
                "verbose_name": "Link di Scraping",
                "verbose_name_plural": "Link di Scraping",
                "ordering": ["competitor", "source"],
                "unique_together": {("competitor", "url")},
            },
        ),
        migrations.CreateModel(
            name="ResortCompetitorAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resort_associations",
                        to="competitors.competitor",
                    ),
                ),
                (
                    "resort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitor_associations",
                        to="resort.resort",
                    ),
                ),
            ],
            options={
                "verbose_name": "Associazione Resort-Competitor",
                "verbose_name_plural": "Associazioni Resort-Competitor",
                "unique_together": {("resort", "competitor")},
            },
        ),
        migrations.CreateModel(
            name="ScrapedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_identifier",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="ID della Fonte"
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        default="review", max_length=50, verbose_name="Tipo di Dato"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=512, null=True, verbose_name="Titolo"
                    ),
                ),
                ("text", models.TextField(blank=True, null=True, verbose_name="Testo")),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        verbose_name="Rating",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Autore"
                    ),
                ),
                (
                    "publication_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data di Pubblicazione"
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(default=dict, verbose_name="Dati Grezzi (JSON)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data di Acquisizione"
                    ),
                ),
                (
                    "scraping_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scraped_data",
                        to="competitors.scrapinglink",
                        verbose_name="Link di Origine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dato Scansionato",
                "verbose_name_plural": "Dati Scansionati",
                "ordering": ["-publication_date", "-created_at"],
                "unique_together": {("scraping_link", "source_identifier")},
            },
        ),
    ]
