# Generated by Django 5.2.4 on 2025-09-15 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitorDataAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sentiment_score",
                    models.FloatField(
                        help_text="Sentiment score from -1 (very negative) to 1 (very positive)"
                    ),
                ),
                (
                    "sentiment_label",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                        ],
                        help_text="Categorical label for the sentiment",
                        max_length=10,
                    ),
                ),
                ("analyzed_at", models.DateTimeField(auto_now=True)),
                (
                    "scraped_data",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="competitors.scrapeddata",
                    ),
                ),
            ],
        ),
    ]
