# Generated by Django 5.2.4 on 2025-08-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlatformSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform_name",
                    models.CharField(default="Noir Tools Kit", max_length=100),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#23395d",
                        help_text="Colore primario in formato esadecimale (es. #RRGGBB)",
                        max_length=7,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#406fa6",
                        help_text="Colore secondario in formato esadecimale (es. #RRGGBB)",
                        max_length=7,
                    ),
                ),
            ],
            options={
                "verbose_name": "Impostazioni Piattaforma",
                "verbose_name_plural": "Impostazioni Piattaforma",
            },
        ),
    ]
