# Generated by Django 5.2.4 on 2025-09-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsettings",
            name="maintenance_mode",
            field=models.BooleanField(
                default=False,
                help_text="Se attivata, solo i Superadmin potranno accedere al sito. Tutti gli altri utenti verranno reindirizzati a una pagina di manutenzione.",
                verbose_name="Attiva Modalità Manutenzione",
            ),
        ),
    ]
