# Generated by Django 5.2.4 on 2025-10-23 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_trusteddevice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InAppGuideAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guide_key", models.CharField(db_index=True, max_length=100)),
                ("step_key", models.CharField(db_index=True, max_length=150)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("image", "Immagine"),
                            ("link", "Link"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField()),
                ("thumbnail_url", models.URLField(blank=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_guide_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Risorsa guida in-app",
                "verbose_name_plural": "Risorse guida in-app",
                "ordering": ("position", "created_at"),
                "indexes": [
                    models.Index(
                        fields=["guide_key", "step_key"],
                        name="core_inappg_guide_k_18b029_idx",
                    )
                ],
            },
        ),
    ]
