# Generated by Django 5.2.4 on 2025-11-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_inappguideasset"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsettings",
            name="marketing_policy_version",
            field=models.CharField(
                default="v1.0",
                help_text="Versione corrente per il consenso marketing/newsletter",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="privacy_policy_version",
            field=models.CharField(
                default="v1.0",
                help_text="Versione corrente dell'informativa Privacy",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="terms_policy_version",
            field=models.CharField(
                default="v1.0",
                help_text="Versione corrente dei Termini e Condizioni",
                max_length=50,
            ),
        ),
    ]
