# Generated by Django 5.2.4 on 2026-03-05 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_adminlogentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NuviaMailAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_address", models.EmailField(max_length=254)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("google", "Google Workspace"),
                            ("microsoft", "Microsoft 365"),
                            ("imap", "IMAP/SMTP generico"),
                        ],
                        default="imap",
                        max_length=20,
                    ),
                ),
                (
                    "auth_mode",
                    models.CharField(
                        choices=[
                            ("oauth", "OAuth"),
                            ("password", "Password"),
                            ("app_password", "App Password"),
                        ],
                        default="app_password",
                        max_length=20,
                    ),
                ),
                ("imap_host", models.CharField(blank=True, max_length=255)),
                ("imap_port", models.PositiveIntegerField(default=993)),
                ("smtp_host", models.CharField(blank=True, max_length=255)),
                ("smtp_port", models.PositiveIntegerField(default=587)),
                ("use_ssl", models.BooleanField(default=True)),
                ("use_starttls", models.BooleanField(default=True)),
                ("username", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("last_test_status", models.CharField(blank=True, max_length=20)),
                ("last_test_message", models.CharField(blank=True, max_length=255)),
                ("last_test_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nuvia_mail_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Account Nuvia Mail",
                "verbose_name_plural": "Account Nuvia Mail",
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="NuviaMailOnboardingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("landing_visit", "Landing visit"),
                            ("account_saved", "Account saved"),
                            ("connection_tested", "Connection tested"),
                            ("signature_saved", "Signature saved"),
                        ],
                        max_length=40,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nuvia_mail_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento onboarding Nuvia Mail",
                "verbose_name_plural": "Eventi onboarding Nuvia Mail",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="NuviaMailSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Firma standard", max_length=80)),
                ("body", models.TextField()),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatures",
                        to="core.nuviamailaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nuvia_mail_signatures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Firma Nuvia Mail",
                "verbose_name_plural": "Firme Nuvia Mail",
                "ordering": ("-is_default", "-updated_at"),
            },
        ),
        migrations.AddConstraint(
            model_name="nuviamailaccount",
            constraint=models.UniqueConstraint(
                fields=("user", "email_address"), name="uniq_nuvia_mail_user_email"
            ),
        ),
        migrations.AddIndex(
            model_name="nuviamailonboardingevent",
            index=models.Index(
                fields=["user", "event_type", "created_at"],
                name="core_nuviam_user_id_eaeb27_idx",
            ),
        ),
    ]
