# Generated by Django 5.2.4 on 2026-03-05 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_nuviamailaccount_nuviamailonboardingevent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="nuviamailonboardingevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("landing_visit", "Landing visit"),
                    ("account_saved", "Account saved"),
                    ("connection_tested", "Connection tested"),
                    ("signature_saved", "Signature saved"),
                    ("queue_item_created", "Queue item created"),
                ],
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="NuviaMailSendQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to_email", models.EmailField(max_length=254)),
                ("cc", models.CharField(blank=True, max_length=255)),
                ("bcc", models.CharField(blank=True, max_length=255)),
                ("subject", models.CharField(max_length=180)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "In coda"),
                            ("sent", "Inviata"),
                            ("failed", "Errore"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="send_queue_items",
                        to="core.nuviamailaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nuvia_mail_send_queue",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Coda invio Nuvia Mail",
                "verbose_name_plural": "Coda invio Nuvia Mail",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="NuviaMailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=180)),
                ("body", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nuvia_mail_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Nuvia Mail",
                "verbose_name_plural": "Template Nuvia Mail",
                "ordering": ("name",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "name"),
                        name="uniq_nuvia_mail_template_user_name",
                    )
                ],
            },
        ),
    ]
