# Generated by Django 5.2.4 on 2026-03-05 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_nuviamailonboardingevent_event_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="nuviamailsendqueue",
            name="compliance_flagged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="nuviamailsendqueue",
            name="compliance_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="NuviaMailCompliancePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enforce_external_domain_block", models.BooleanField(default=False)),
                (
                    "allowed_domains",
                    models.TextField(
                        blank=True,
                        help_text="Domini consentiti separati da virgola, es: azienda.it,partner.com",
                    ),
                ),
                (
                    "sensitive_keywords",
                    models.TextField(
                        blank=True,
                        help_text="Parole chiave sensibili separate da virgola.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nuvia_mail_compliance_policy",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy compliance Nuvia Mail",
                "verbose_name_plural": "Policy compliance Nuvia Mail",
            },
        ),
    ]
