# Generated by Django 5.2.4 on 2026-03-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_nuviamailsendqueue_compliance_flagged_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nuviamailsendqueue",
            name="last_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nuviamailsendqueue",
            name="max_retries",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="nuviamailsendqueue",
            name="provider_message_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="nuviamailsendqueue",
            name="retry_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="nuviamailonboardingevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("landing_visit", "Landing visit"),
                    ("account_saved", "Account saved"),
                    ("connection_tested", "Connection tested"),
                    ("signature_saved", "Signature saved"),
                    ("queue_item_created", "Queue item created"),
                    ("queue_processed", "Queue processed"),
                ],
                max_length=40,
            ),
        ),
    ]
