# Generated by Django 5.2.4 on 2026-03-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_nuviamailsendqueue_last_attempt_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nuviamailcompliancepolicy",
            name="blocked_domains",
            field=models.TextField(
                blank=True, help_text="Domini sempre bloccati separati da virgola."
            ),
        ),
        migrations.AddField(
            model_name="nuviamailcompliancepolicy",
            name="blocked_recipients",
            field=models.TextField(
                blank=True,
                help_text="Indirizzi email sempre bloccati separati da virgola.",
            ),
        ),
        migrations.AddField(
            model_name="nuviamailcompliancepolicy",
            name="flagged_action",
            field=models.CharField(
                choices=[
                    ("mark_failed", "Blocca invio"),
                    ("require_approval", "Richiedi approvazione"),
                ],
                default="require_approval",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="nuviamailcompliancepolicy",
            name="sensitive_regex_patterns",
            field=models.TextField(
                blank=True, help_text="Pattern regex sensibili separati da virgola."
            ),
        ),
        migrations.AlterField(
            model_name="nuviamailsendqueue",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "In coda"),
                    ("sent", "Inviata"),
                    ("failed", "Errore"),
                    ("pending_approval", "In attesa approvazione"),
                ],
                default="queued",
                max_length=20,
            ),
        ),
    ]
