# Generated by Django 5.2.4 on 2026-03-06 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_nuviamailcompliancepolicy_blocked_domains_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="nuviamailonboardingevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("landing_visit", "Landing visit"),
                    ("account_saved", "Account saved"),
                    ("connection_tested", "Connection tested"),
                    ("signature_saved", "Signature saved"),
                    ("queue_item_created", "Queue item created"),
                    ("queue_processed", "Queue processed"),
                    ("queue_item_approved", "Queue item approved"),
                    ("queue_item_rejected", "Queue item rejected"),
                ],
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="NuviaMailFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_folder_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=120)),
                ("is_inbox", models.BooleanField(default=False)),
                ("is_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folders",
                        to="core.nuviamailaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nuvia_mail_folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cartella Nuvia Mail",
                "verbose_name_plural": "Cartelle Nuvia Mail",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="NuviaMailSyncCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cursor", models.CharField(blank=True, max_length=255)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_checkpoints",
                        to="core.nuviamailaccount",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_checkpoints",
                        to="core.nuviamailfolder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nuvia_mail_sync_checkpoints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Checkpoint sync Nuvia Mail",
                "verbose_name_plural": "Checkpoint sync Nuvia Mail",
            },
        ),
        migrations.CreateModel(
            name="NuviaMailThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_thread_id", models.CharField(blank=True, max_length=255)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threads",
                        to="core.nuviamailaccount",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threads",
                        to="core.nuviamailfolder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nuvia_mail_threads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Thread Nuvia Mail",
                "verbose_name_plural": "Thread Nuvia Mail",
                "ordering": ("-last_message_at", "-updated_at"),
            },
        ),
        migrations.CreateModel(
            name="NuviaMailMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_message_id", models.CharField(max_length=255)),
                ("message_id_header", models.CharField(blank=True, max_length=255)),
                ("in_reply_to", models.CharField(blank=True, max_length=255)),
                ("references_header", models.TextField(blank=True)),
                ("from_email", models.EmailField(blank=True, max_length=254)),
                ("to_emails", models.TextField(blank=True)),
                ("cc_emails", models.TextField(blank=True)),
                ("bcc_emails", models.TextField(blank=True)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("body_text", models.TextField(blank=True)),
                ("body_html", models.TextField(blank=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.nuviamailaccount",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.nuviamailfolder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nuvia_mail_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.nuviamailthread",
                    ),
                ),
            ],
            options={
                "verbose_name": "Messaggio Nuvia Mail",
                "verbose_name_plural": "Messaggi Nuvia Mail",
                "ordering": ("-received_at", "-created_at"),
            },
        ),
        migrations.AddConstraint(
            model_name="nuviamailfolder",
            constraint=models.UniqueConstraint(
                fields=("account", "provider_folder_id"),
                name="uniq_nuvia_mail_folder_provider_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="nuviamailsynccheckpoint",
            constraint=models.UniqueConstraint(
                fields=("account", "folder"),
                name="uniq_nuvia_mail_sync_checkpoint_folder",
            ),
        ),
        migrations.AddIndex(
            model_name="nuviamailthread",
            index=models.Index(
                fields=["user", "last_message_at"],
                name="core_nuviam_user_id_d19ec1_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="nuviamailmessage",
            constraint=models.UniqueConstraint(
                fields=("account", "provider_message_id"),
                name="uniq_nuvia_mail_message_provider_id",
            ),
        ),
    ]
