# Generated by Django 5.2.4 on 2026-03-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_nuviamailonboardingevent_event_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nuviamailaccount",
            name="oauth_access_token_masked",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="nuviamailaccount",
            name="oauth_connected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nuviamailaccount",
            name="oauth_refresh_token_masked",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="nuviamailaccount",
            name="oauth_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
