# Generated by Django 5.2.4 on 2026-03-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_nuviamailaccount_oauth_access_token_masked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nuviamailaccount",
            name="encrypted_oauth_access_token",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="nuviamailaccount",
            name="encrypted_oauth_refresh_token",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="nuviamailaccount",
            name="encrypted_password",
            field=models.TextField(blank=True),
        ),
    ]
