# Generated by Django 5.2.4 on 2025-08-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resort", "0003_add_room_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resort",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
