# Generated by Django 5.2.4 on 2025-08-19 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_company_delete_client"),
        ("resort", "0004_make_resort_name_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="resort",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resorts",
                to="clients.company",
            ),
        ),
    ]
