# Generated by Django 5.2.4 on 2025-09-26 01:01

from django.db import migrations

def create_initial_resorts(apps, schema_editor):
    """
    Crea i resort iniziali necessari per i dati di test.
    """
    Resort = apps.get_model('resort', 'Resort')
    Resort.objects.get_or_create(name='Resort Paradiso')
    Resort.objects.get_or_create(name='Resort Montagna Incantata')

class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0005_resort_company'),
    ]

    operations = [
        migrations.RunPython(create_initial_resorts),
    ]