# Generated by Django 5.2.4 on 2025-08-25 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
        ("resort", "0005_resort_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="resort",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="resort.resort",
            ),
        ),
    ]
