# Generated by Django 5.2.4 on 2025-08-25 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_asset_resort"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="assigned_to",
        ),
    ]
