# Generated by Django 5.2.4 on 2025-08-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_remove_asset_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="purchase_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Costo di Acquisto",
            ),
        ),
    ]
