# Generated by Django 5.2.4 on 2025-09-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_company_delete_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Logo della società, mostrato nei report.",
                null=True,
                upload_to="company_logos/",
            ),
        ),
    ]
