# Generated by Django 5.2.4 on 2025-11-04 09:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_company_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Structure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome pubblico della struttura.", max_length=255
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Slug univoco per i collegamenti rapidi.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrizione breve o note interne sulla struttura.",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Europe/Rome",
                        help_text="Fuso orario utilizzato per pianificazioni e generazione documenti.",
                        max_length=100,
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Indirizzo della struttura.",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Indica se la struttura è operativa."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Società proprietaria della struttura.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structures",
                        to="clients.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Struttura",
                "verbose_name_plural": "Strutture",
                "ordering": ["company__name", "name"],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.CreateModel(
            name="StructureRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome del ruolo (es. Chef, Maître).", max_length=150
                    ),
                ),
                (
                    "can_edit_layouts",
                    models.BooleanField(
                        default=False,
                        help_text="Può creare e modificare i layout grafici per menu e cavalieri.",
                    ),
                ),
                (
                    "can_publish_menu",
                    models.BooleanField(
                        default=False,
                        help_text="Può pubblicare e generare documenti ufficiali dei menu.",
                    ),
                ),
                (
                    "can_manage_allergens",
                    models.BooleanField(
                        default=True,
                        help_text="Può aggiungere/aggiornare ingredienti e allergeni.",
                    ),
                ),
                (
                    "can_manage_templates",
                    models.BooleanField(
                        default=False,
                        help_text="Può creare e modificare template di cavalieri e bundle di documenti.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Società proprietaria del ruolo.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structure_roles",
                        to="clients.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ruolo Struttura",
                "verbose_name_plural": "Ruoli Struttura",
                "ordering": ["company__name", "name"],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.CreateModel(
            name="StructureMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Se disattivato l'utente non può operare nella struttura.",
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Data di inizio validità del ruolo.",
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        help_text="Data di fine validità, opzionale.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "structure",
                    models.ForeignKey(
                        help_text="Struttura di appartenenza.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="clients.structure",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Utente assegnato alla struttura.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structure_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ruolo assegnato all'utente.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memberships",
                        to="clients.structurerole",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membro Struttura",
                "verbose_name_plural": "Membri Struttura",
                "ordering": [
                    "structure__company__name",
                    "structure__name",
                    "user__username",
                ],
                "unique_together": {("user", "structure", "role")},
            },
        ),
    ]
