# Generated by Django 5.2.4 on 2025-11-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_structure_structurerole_structuremembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="structurerole",
            name="can_approve_menu",
            field=models.BooleanField(
                default=False,
                help_text="Può approvare menu e versioni prima della pubblicazione.",
            ),
        ),
        migrations.AddField(
            model_name="structurerole",
            name="can_edit_dishes",
            field=models.BooleanField(
                default=True,
                help_text="Può creare, aggiornare e cancellare piatti nel catalogo aziendale.",
            ),
        ),
        migrations.AddField(
            model_name="structurerole",
            name="can_edit_menus",
            field=models.BooleanField(
                default=True,
                help_text="Può creare e modificare i menu (dati base e composizione).",
            ),
        ),
    ]
