# Generated by Django 5.2.4 on 2025-08-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_index_to_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_maintenance_access",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="has_reviews_access",
            field=models.BooleanField(default=False),
        ),
    ]
