# Generated by Django 5.2.4 on 2025-08-19 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_role"),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Il cliente a cui questo utente appartiene.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="clients.client",
            ),
        ),
    ]
