# Generated by Django 5.2.4 on 2025-08-19 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_user_client"),
        ("clients", "0002_company_delete_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="La società a cui questo utente appartiene.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="clients.company",
            ),
        ),
    ]
