# Generated by Django 5.2.4 on 2025-08-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("receptionist", "Receptionist"),
                    ("maintainer", "Manutentore"),
                    ("housekeeping", "Housekeeping"),
                    ("director", "Direttore"),
                    ("owner", "Proprietario"),
                    ("superadmin", "Super Admin"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
