# Generated by Django 5.2.4 on 2025-08-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_user_last_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gamertag",
            field=models.CharField(
                blank=True,
                help_text="Nickname univoco per la sezione svago",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
