# Generated by Django 5.2.4 on 2025-08-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_manage_purchase_orders",
            field=models.BooleanField(
                default=False,
                help_text="Se selezionato, l'utente potrà creare e gestire i buoni d'ordine.",
                verbose_name="Abilita Gestione Buoni d'Ordine",
            ),
        ),
    ]
