# Generated by Django 5.2.4 on 2025-08-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_user_can_manage_purchase_orders"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_inventory_access",
            field=models.BooleanField(
                default=False,
                help_text="Se selezionato, l'utente potrà visualizzare e gestire l'inventario.",
                verbose_name="Abilita Gestione Inventario",
            ),
        ),
    ]
