# Generated by Django 5.2.4 on 2025-09-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_user_has_inventory_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_export_review_reports",
            field=models.BooleanField(
                default=False,
                help_text="Consente all'utente di generare ed esportare report di recensioni in formato PDF.",
                verbose_name="Può Esportare Report Recensioni",
            ),
        ),
    ]
