# Generated by Django 5.2.4 on 2025-09-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_can_export_review_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_concierge_access',
            field=models.BooleanField(default=False),
        ),
    ]
