# Generated by Django 5.2.4 on 2025-09-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_user_has_concierge_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_2fa_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Autenticazione a Due Fattori Abilitata"
            ),
        ),
    ]
