# Generated by Django 5.2.4 on 2025-09-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_user_is_2fa_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_last_changed",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Ultima Modifica Password"
            ),
        ),
    ]
