# Generated by Django 5.2.4 on 2025-09-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_user_password_last_changed"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_it_support_management_access",
            field=models.BooleanField(
                default=False,
                help_text="Se selezionato, l'utente potrà gestire i ticket di supporto IT (non solo crearli).",
                verbose_name="Abilita Gestione Supporto IT",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("receptionist", "Receptionist"),
                    ("maintainer", "Manutentore"),
                    ("housekeeping", "Housekeeping"),
                    ("director", "Direttore"),
                    ("owner", "Proprietario"),
                    ("administrative", "Amministrativo"),
                    ("corporate", "Corporate"),
                    ("it_technician", "Tecnico IT"),
                    ("superadmin", "Super Admin"),
                    ("economo", "Economo"),
                    ("capo_economo", "Capo Economo"),
                    ("risorse_umane", "Risorse Umane"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
