# Generated by Django 5.2.4 on 2025-09-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_user_has_it_support_management_access_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("receptionist", "Receptionist"),
                    ("maintainer", "Manutentore"),
                    ("head_maintainer", "Capomanutentore"),
                    ("housekeeping", "Housekeeping"),
                    ("director", "Direttore"),
                    ("owner", "Proprietario"),
                    ("administrative", "Amministrativo"),
                    ("corporate", "Corporate"),
                    ("it_technician", "Tecnico IT"),
                    ("superadmin", "Super Admin"),
                    ("economo", "Economo"),
                    ("capo_economo", "Capo Economo"),
                    ("risorse_umane", "Risorse Umane"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
