# Generated by Django 5.2.4 on 2025-09-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_alter_user_role"),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="skills.skill",
                verbose_name="Competenze",
            ),
        ),
    ]
