# Generated by Django 5.2.4 on 2025-09-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_user_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="background_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="user_backgrounds/",
                verbose_name="Immagine di Sfondo",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="theme",
            field=models.CharField(
                choices=[
                    ("light", "Chiaro"),
                    ("dark", "Scuro"),
                    ("auto", "Automatico (sistema)"),
                ],
                default="auto",
                max_length=10,
                verbose_name="Tema Grafico",
            ),
        ),
    ]
