# Generated by Django 5.2.4 on 2025-09-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_user_background_image_user_theme"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="background_image",
        ),
        migrations.AddField(
            model_name="user",
            name="background_image_desktop",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="user_backgrounds/desktop/",
                verbose_name="Sfondo Desktop",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="background_image_mobile",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="user_backgrounds/mobile/",
                verbose_name="Sfondo Mobile",
            ),
        ),
    ]
