# Generated by Django 5.2.4 on 2025-11-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_remove_user_background_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="receives_unassigned_ticket_alerts",
            field=models.BooleanField(
                default=True,
                help_text="Se disattivato, l'utente non riceverà promemoria sui ticket di manutenzione non assegnati.",
                verbose_name="Riceve avvisi ticket non assegnati",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("receptionist", "Receptionist"),
                    ("maintainer", "Manutentore"),
                    ("head_maintainer", "Capomanutentore"),
                    ("maintenance_manager", "Responsabile Manutenzione"),
                    ("housekeeping", "Housekeeping"),
                    ("director", "Direttore"),
                    ("owner", "Proprietario"),
                    ("administrative", "Amministrativo"),
                    ("corporate", "Corporate"),
                    ("it_technician", "Tecnico IT"),
                    ("superadmin", "Super Admin"),
                    ("economo", "Economo"),
                    ("capo_economo", "Capo Economo"),
                    ("risorse_umane", "Risorse Umane"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
