# Generated by Django 5.2.4 on 2025-11-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_user_receives_unassigned_ticket_alerts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="menu_creation_studio_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Se selezionato, l'utente potrà accedere allo strumento di creazione menu.",
                verbose_name="Abilita Menu Creation Studio",
            ),
        ),
    ]
