# Generated by Django 5.2.4 on 2025-11-18 15:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0005_structurerole_can_approve_menu_and_more"),
        ("hr_portal", "0001_initial"),
        ("resort", "0006_seed_resorts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayslipUnmatched",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "identifier",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("file", models.FileField(upload_to="hr/payslips/unmatched/")),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="hrdocument",
            new_name="hr_portal_h_categor_1f137d_idx",
            old_name="hr_portal_h_category_4388b6_idx",
        ),
        migrations.RenameIndex(
            model_name="hrdocument",
            new_name="hr_portal_h_visible_05776c_idx",
            old_name="hr_portal_h_visible__6c16e2_idx",
        ),
        migrations.RenameIndex(
            model_name="listeningticket",
            new_name="hr_portal_l_status_ff836e_idx",
            old_name="hr_portal_l_status__3e66c8_idx",
        ),
        migrations.RenameIndex(
            model_name="payslip",
            new_name="hr_portal_p_status_fb30c2_idx",
            old_name="hr_portal_p_status__6b23eb_idx",
        ),
        migrations.AddField(
            model_name="payslipunmatched",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unmatched_items",
                to="hr_portal.payslipbatch",
            ),
        ),
        migrations.AddField(
            model_name="payslipunmatched",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clients.company",
            ),
        ),
        migrations.AddField(
            model_name="payslipunmatched",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_payslip_unmatched_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payslipunmatched",
            name="resolved_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_payslip_unmatched",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payslipunmatched",
            name="resort",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="resort.resort",
            ),
        ),
        migrations.AddIndex(
            model_name="payslipunmatched",
            index=models.Index(
                fields=["resolved", "created_at"], name="hr_portal_p_resolve_64f513_idx"
            ),
        ),
    ]
