# Generated by Django 5.2.4 on 2025-11-18 15:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0005_structurerole_can_approve_menu_and_more"),
        ("hr_portal", "0004_payslipbatch_ocr_fields"),
        ("resort", "0006_seed_resorts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="listeningticket",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listeningticket",
            name="due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listeningticket",
            name="sla_hours",
            field=models.PositiveIntegerField(
                default=72, help_text="SLA orario per la gestione del ticket"
            ),
        ),
        migrations.AddField(
            model_name="payslipbatch",
            name="auto_match_rate",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="payslipbatch",
            name="processing_duration_ms",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="HREventLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("document_ack", "ACK Documento"),
                            ("payslip_download", "Download Busta Paga"),
                            ("payslip_resolved", "Busta Paga assegnata manualmente"),
                            ("ticket_escalated", "Ticket escalato"),
                            ("ticket_closed", "Ticket chiuso"),
                        ],
                        max_length=64,
                    ),
                ),
                ("target_model", models.CharField(max_length=128)),
                ("target_id", models.CharField(max_length=128)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clients.company",
                    ),
                ),
                (
                    "resort",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="resort.resort",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="hr_portal_h_event_t_12fb33_idx",
                    ),
                    models.Index(
                        fields=["company", "resort", "created_at"],
                        name="hr_portal_h_company_2d1308_idx",
                    ),
                ],
            },
        ),
    ]
