# Generated by Django 5.2.4 on 2025-11-18 15:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_portal", "0006_notificationpreference_hrnotification_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="hreventlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("document_ack", "ACK Documento"),
                    ("payslip_download", "Download Busta Paga"),
                    ("payslip_resolved", "Busta Paga assegnata manualmente"),
                    ("payslip_notified", "Notifica disponibilità busta paga"),
                    ("notification_delivered", "Notifica consegnata"),
                    ("ticket_escalated", "Ticket escalato"),
                    ("ticket_closed", "Ticket chiuso"),
                ],
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="HRNotificationDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("push", "Push"), ("sms", "SMS")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "In attesa"),
                            ("delivered", "Consegnato"),
                            ("failed", "Fallito"),
                            ("skipped", "Ignorato"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="hr_portal.hrnotification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "sent_at"],
                        name="hr_portal_h_status_a02d55_idx",
                    )
                ],
                "unique_together": {("notification", "user", "channel")},
            },
        ),
    ]
