# Generated by Django 5.2.4 on 2025-11-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_portal", "0007_alter_hreventlog_event_type_hrnotificationdelivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hreventlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("document_ack", "ACK Documento"),
                    ("payslip_download", "Download Busta Paga"),
                    ("payslip_resolved", "Busta Paga assegnata manualmente"),
                    ("payslip_notified", "Notifica disponibilità busta paga"),
                    ("payslip_batch_started", "Batch buste paga avviato"),
                    ("payslip_batch_completed", "Batch buste paga completato"),
                    ("payslip_batch_failed", "Batch buste paga fallito"),
                    ("payslip_batch_created", "Batch buste paga creato"),
                    ("notification_delivered", "Notifica consegnata"),
                    ("notification_published", "Notifica pubblicata"),
                    ("notification_archived", "Notifica archiviata"),
                    ("notification_delivery_failed", "Notifica fallita"),
                    ("notification_created", "Notifica creata"),
                    ("notification_updated", "Notifica aggiornata"),
                    ("notification_status_changed", "Stato notifica aggiornato"),
                    ("ticket_escalated", "Ticket escalato"),
                    ("ticket_closed", "Ticket chiuso"),
                    ("ticket_assigned", "Ticket assegnato"),
                    ("ticket_created", "Ticket creato"),
                    ("ticket_message", "Messaggio ticket"),
                ],
                max_length=64,
            ),
        ),
    ]
