# Generated by Django 5.2.4 on 2025-11-18 00:00

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0005_structurerole_can_approve_menu_and_more"),
        ("resort", "0006_seed_resorts"),
        ("hr_portal", "0009_alter_payslip_file_lengths"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayslipEmailRecipient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=255)),
                ("used_count", models.PositiveIntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.company",
                    ),
                ),
                (
                    "resort",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resort.resort",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_used_at", "-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="payslipemailrecipient",
            unique_together={("email", "company", "resort")},
        ),
        migrations.AddIndex(
            model_name="payslipemailrecipient",
            index=models.Index(fields=["email", "company", "resort"], name="hr_portal_p_email_51ac44_idx"),
        ),
    ]
