# Generated by Django 5.2.4 on 2025-09-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desk", "0002_alter_widgetpreference_options_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("event", "Evento"),
                    ("task", "Task"),
                    ("appointment", "Appuntamento"),
                ],
                default="event",
                max_length=20,
            ),
        ),
    ]
