# Generated by Django 5.2.4 on 2025-09-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desk", "0003_event_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="widgetpreference",
            name="layout",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="A dictionary of layouts for different breakpoints, e.g., {'lg': [...], 'md': [...]}",
            ),
        ),
    ]
