# Generated by Django 5.2.4 on 2025-09-22 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desk", "0004_alter_widgetpreference_layout"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"verbose_name": "Evento", "verbose_name_plural": "Eventi"},
        ),
        migrations.AlterField(
            model_name="event",
            name="user",
            field=models.ForeignKey(
                help_text="The user who created the event.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="EventInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="desk.event",
                    ),
                ),
                (
                    "invitee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Invito Evento",
                "verbose_name_plural": "Inviti Evento",
                "unique_together": {("event", "invitee")},
            },
        ),
        migrations.AddField(
            model_name="event",
            name="attendees",
            field=models.ManyToManyField(
                help_text="Users who are invited to this event.",
                related_name="attended_events",
                through="desk.EventInvitation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
