# Generated by Django 5.2.4 on 2026-03-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desk", "0005_alter_event_options_alter_event_user_eventinvitation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="widgetpreference",
            name="open_windows",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="A list of window IDs currently open on the desktop",
            ),
        ),
    ]
