# Generated by Django 5.2.4 on 2026-03-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desk", "0006_widgetpreference_open_windows"),
    ]

    operations = [
        migrations.AddField(
            model_name="widgetpreference",
            name="pinned_icons",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="A list of app IDs pinned to the desktop icons",
            ),
        ),
    ]
