# Generated by Django 5.2.4 on 2026-03-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desk", "0007_widgetpreference_pinned_icons"),
    ]

    operations = [
        migrations.AddField(
            model_name="widgetpreference",
            name="active_workspace_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="widgetpreference",
            name="workspaces",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Definition of virtual desktops/workspaces",
            ),
        ),
    ]
