# Generated by Django 5.2.4 on 2025-09-12 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The display name of the sector, e.g., 'Manutenzione'.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "role_key",
                    models.CharField(
                        help_text="The internal key for the role, e.g., 'maintainer'.",
                        max_length=30,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Procedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titolo")),
                (
                    "file",
                    models.FileField(upload_to="procedures/", verbose_name="File PDF"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data di Creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data Ultimo Aggiornamento"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Versione"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_procedures",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Caricato da",
                    ),
                ),
                (
                    "sectors",
                    models.ManyToManyField(
                        related_name="procedures",
                        to="procedures.sector",
                        verbose_name="Settori di pertinenza",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procedura",
                "verbose_name_plural": "Procedure",
                "ordering": ["-updated_at"],
            },
        ),
    ]
