# Generated by Django 5.2.4 on 2025-09-12 06:48

from django.db import migrations

# It's important to import the User model from accounts to access ROLE_CHOICES
# However, in migrations, we should not import models directly.
# We get them from the historical app registry.
# But for accessing constants like ROLE_CHOICES, we must import the model.
from accounts.models import User

def populate_sectors(apps, schema_editor):
    """
    Populates the Sector table with all the roles defined in User.ROLE_CHOICES.
    """
    Sector = apps.get_model('procedures', 'Sector')
    for role_key, role_name in User.ROLE_CHOICES:
        Sector.objects.get_or_create(role_key=role_key, defaults={'name': role_name})

def delete_all_sectors(apps, schema_editor):
    """
    Deletes all sectors. This is the reverse operation.
    """
    Sector = apps.get_model('procedures', 'Sector')
    Sector.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0001_initial"),
        # We add a dependency on the latest accounts migration to ensure
        # the User model and its ROLE_CHOICES are available.
        ("accounts", "0021_user_has_it_support_management_access_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_sectors, reverse_code=delete_all_sectors),
    ]
