# Generated by Django 5.2.4 on 2025-09-17 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_company_logo"),
        ("procedures", "0002_populate_sectors"),
    ]

    operations = [
        migrations.AddField(
            model_name="procedure",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="procedures",
                to="clients.company",
                verbose_name="Azienda",
            ),
        ),
    ]
