# Generated by Django 5.2.4 on 2025-09-17 02:24

from django.db import migrations, models

def populate_procedure_company(apps, schema_editor):
    """
    Populates the 'company' field for all existing Procedure records.

    This migration handles the edge case where Procedures exist in the
    database but no Companies have been created yet.

    Logic:
    1. It first checks if any companies exist.
    2. If NO companies exist, it creates a placeholder company named
       "Azienda da Assegnare".
    3. It then assigns this default company to any procedure that doesn't
       have a company, prioritizing the company of the user who uploaded
       the procedure if available.
    """
    Procedure = apps.get_model('procedures', 'Procedure')
    Company = apps.get_model('clients', 'Company')

    # If there are no procedures to update, we can exit early.
    if not Procedure.objects.exists():
        return

    # Get the first company to use as a default.
    default_company = Company.objects.order_by('pk').first()

    # If no companies exist in the database, create a placeholder.
    # This is the critical fix for the user's deployment issue.
    if not default_company:
        print("No companies found. Creating a placeholder 'Azienda da Assegnare'.")
        default_company = Company.objects.create(name="Azienda da Assegnare")

    # Iterate over all procedures that still need a company assigned.
    for procedure in Procedure.objects.filter(company__isnull=True):
        # Prefer the uploader's company if it exists.
        if hasattr(procedure, 'uploaded_by') and procedure.uploaded_by and procedure.uploaded_by.company:
            procedure.company = procedure.uploaded_by.company
        # Otherwise, fall back to the default company.
        else:
            procedure.company = default_company

        procedure.save()


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0003_procedure_company'),
        ('clients', '0001_initial'),
        ('accounts', '0008_user_company'),
    ]

    operations = [
        migrations.RunPython(populate_procedure_company, reverse_code=migrations.RunPython.noop),
    ]
