# Generated by Django 5.2.4 on 2025-09-17 01:45

from django.db import migrations, models
import django.db.models.deletion
from clients.models import Company


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0004_populate_procedure_company'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='clients.company', verbose_name='Azienda'),
        ),
    ]
