# Generated by Django 5.2.4 on 2025-08-29 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("purchase_orders", "0002_budget"),
        ("resort", "0005_resort_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nome Articolo"),
                ),
                (
                    "product_code",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Codice Prodotto/SKU",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrizione"),
                ),
                (
                    "current_stock",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Giacenza Attuale"
                    ),
                ),
                (
                    "resort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="resort.resort",
                        verbose_name="Resort",
                    ),
                ),
            ],
            options={
                "verbose_name": "Articolo in Inventario",
                "verbose_name_plural": "Articoli in Inventario",
                "ordering": ["resort", "name"],
                "unique_together": {("resort", "product_code")},
            },
        ),
        migrations.CreateModel(
            name="StockRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("change", models.IntegerField(verbose_name="Variazione (+/-)")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data e Ora"),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("initial", "Giacenza Iniziale"),
                            ("purchase", "Entrata da Ordine"),
                            ("withdrawal", "Prelievo/Utilizzo"),
                            ("adjustment", "Rettifica Manuale"),
                            ("return", "Reso"),
                        ],
                        max_length=20,
                        verbose_name="Motivo",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="Note")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_records",
                        to="inventory.inventoryitem",
                        verbose_name="Articolo",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_records",
                        to="purchase_orders.purchaseorder",
                        verbose_name="Rif. Buono d'Ordine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimento di Magazzino",
                "verbose_name_plural": "Movimenti di Magazzino",
                "ordering": ["-timestamp"],
            },
        ),
    ]
