# Generated by Django 5.2.4 on 2025-10-23 08:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0003_company_logo"),
        ("economato", "0001_initial"),
        ("purchase_orders", "0004_purchasecategory_alter_budget_options_and_more"),
        ("resort", "0006_seed_resorts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "category_type",
                    models.CharField(
                        choices=[("revenue", "Ricavo"), ("cost", "Costo")],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Colore per grafici/dashboard (es. 'primary', '#0d6efd').",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Società di riferimento per la categoria (opzionale per categorie globali).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_categories",
                        to="clients.company",
                    ),
                ),
                (
                    "economato_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Collega la categoria all'economato per la lettura dei budget di reparto.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_categories",
                        to="economato.economatocategory",
                    ),
                ),
                (
                    "purchase_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Collega la categoria al catalogo acquisti per insight automatici.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_categories",
                        to="purchase_orders.purchasecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria Finanziaria",
                "verbose_name_plural": "Categorie Finanziarie",
                "ordering": ["name"],
                "unique_together": {("company", "name", "category_type")},
            },
        ),
        migrations.CreateModel(
            name="FinancialDataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("manual", "Inserimento Manuale"),
                            ("api", "Integrazione API"),
                            ("file", "Importazione File"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Società che utilizza la sorgente dati (opzionale per sorgenti condivise).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_data_sources",
                        to="clients.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sorgente Dati Finanziaria",
                "verbose_name_plural": "Sorgenti Dati Finanziarie",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FinancialImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "In Elaborazione"),
                            ("success", "Completato"),
                            ("failed", "Fallito"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("imported_records", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_batches",
                        to="financials.financialdatasource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch Importazione Finanziaria",
                "verbose_name_plural": "Batch Importazione Finanziaria",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="FinancialPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Mensile"),
                            ("quarterly", "Trimestrale"),
                            ("yearly", "Annuale"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Blocca il periodo per evitare modifiche accidentali ai dati contabilizzati.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Società a cui appartiene il periodo.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_periods",
                        to="clients.company",
                    ),
                ),
                (
                    "resort",
                    models.ForeignKey(
                        blank=True,
                        help_text="Resort specifico del periodo (opzionale per viste aggregate).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_periods",
                        to="resort.resort",
                    ),
                ),
            ],
            options={
                "verbose_name": "Periodo Finanziario",
                "verbose_name_plural": "Periodi Finanziari",
                "ordering": ["-year", "-month"],
                "unique_together": {
                    ("company", "resort", "period_type", "year", "month")
                },
            },
        ),
        migrations.CreateModel(
            name="FinancialSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "snapshot_type",
                    models.CharField(
                        choices=[
                            ("budget", "Budget"),
                            ("actual", "Consuntivo"),
                            ("previous_year", "Anno Precedente"),
                            ("forecast", "Previsione"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "total_costs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("currency", models.CharField(default="EUR", max_length=8)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snapshots",
                        to="financials.financialdatasource",
                    ),
                ),
                (
                    "import_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snapshots",
                        to="financials.financialimportbatch",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="financials.financialperiod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Snapshot Finanziario",
                "verbose_name_plural": "Snapshot Finanziari",
                "ordering": ["-period__year", "-period__month", "snapshot_type"],
                "unique_together": {("period", "snapshot_type")},
            },
        ),
        migrations.CreateModel(
            name="FinancialLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line_type",
                    models.CharField(
                        choices=[("revenue", "Ricavo"), ("cost", "Costo")],
                        default="cost",
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "budget",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_line_items",
                        to="purchase_orders.budget",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="line_items",
                        to="financials.financialcategory",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_line_items",
                        to="economato.economatocostcenter",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="financials.financialsnapshot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voce di Dettaglio Finanziaria",
                "verbose_name_plural": "Voci di Dettaglio Finanziarie",
                "ordering": ["-created_at"],
            },
        ),
    ]
