# Generated by Django 5.2.4 on 2025-08-25 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="read_by",
            field=models.ManyToManyField(
                blank=True, related_name="read_documents", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
