# Generated by Django 5.2.4 on 2025-08-19 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("resort", "0004_make_resort_name_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the review source (e.g., Booking.com)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        blank=True,
                        help_text="Base URL of the review source",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "scraper_identifier",
                    models.CharField(
                        blank=True,
                        help_text="Identifier for the Apify scraper task/actor",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_id",
                    models.CharField(
                        help_text="Unique ID of the review from the source platform",
                        max_length=255,
                    ),
                ),
                ("author", models.CharField(blank=True, max_length=255)),
                (
                    "rating",
                    models.FloatField(
                        help_text="The rating given in the review (e.g., 4.5, 9.2)"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("text", models.TextField(blank=True)),
                (
                    "review_date",
                    models.DateTimeField(
                        help_text="The original date and time the review was published"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this review was saved into our system",
                    ),
                ),
                (
                    "resort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="resort.resort",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="reviews.reviewsource",
                    ),
                ),
            ],
            options={
                "ordering": ["-review_date"],
            },
        ),
        migrations.CreateModel(
            name="ReviewAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sentiment_score",
                    models.FloatField(
                        help_text="Sentiment score from -1 (very negative) to 1 (very positive)"
                    ),
                ),
                (
                    "sentiment_label",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                        ],
                        help_text="Categorical label for the sentiment",
                        max_length=10,
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of extracted keywords or topics",
                    ),
                ),
                (
                    "analyzed_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the analysis was last performed"
                    ),
                ),
                (
                    "review",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="reviews.review",
                    ),
                ),
            ],
            options={
                "ordering": ["-analyzed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["resort", "review_date"], name="reviews_rev_resort__f23f58_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["rating"], name="reviews_rev_rating_2db6dd_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("source", "review_id")},
        ),
    ]
