# Generated by Django 5.2.4 on 2025-08-20 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resort", "0005_resort_company"),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapingURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="The specific URL for the resort on the review platform.",
                        max_length=1024,
                    ),
                ),
                (
                    "resort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scraping_urls",
                        to="resort.resort",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scraping_urls",
                        to="reviews.reviewsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "URL da Scansionare",
                "verbose_name_plural": "URL da Scansionare",
                "unique_together": {("resort", "source")},
            },
        ),
    ]
