# Generated by Django 5.2.4 on 2025-08-20 10:59

from django.db import migrations

def create_initial_review_sources(apps, schema_editor):
    """
    Creates the initial set of review sources for the application.
    """
    ReviewSource = apps.get_model('reviews', 'ReviewSource')
    db_alias = schema_editor.connection.alias

    sources = [
        {'name': 'Tripadvisor', 'scraper_identifier': 'tripadvisor'},
        {'name': 'Booking.com', 'scraper_identifier': 'booking-com'},
        {'name': 'Google Maps', 'scraper_identifier': 'google-maps'},
    ]

    for source_data in sources:
        ReviewSource.objects.using(db_alias).update_or_create(
            name=source_data['name'],
            defaults={'scraper_identifier': source_data['scraper_identifier']}
        )

class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_scrapingurl"),
    ]

    operations = [
        migrations.RunPython(create_initial_review_sources),
    ]
