# Generated by Django 5.2.4 on 2025-08-20 11:53

from django.db import migrations

def update_scraper_id(apps, schema_editor):
    """
    Updates the scraper_identifier for the Tripadvisor source.
    """
    ReviewSource = apps.get_model('reviews', 'ReviewSource')
    db_alias = schema_editor.connection.alias
    ReviewSource.objects.using(db_alias).filter(name='Tripadvisor').update(
        scraper_identifier='maxcopell/tripadvisor-reviews'
    )

def revert_scraper_id(apps, schema_editor):
    """
    Reverts the scraper_identifier for the Tripadvisor source to the old value.
    """
    ReviewSource = apps.get_model('reviews', 'ReviewSource')
    db_alias = schema_editor.connection.alias
    ReviewSource.objects.using(db_alias).filter(name='Tripadvisor').update(
        scraper_identifier='tripadvisor'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_populate_review_sources'),
    ]

    operations = [
        migrations.RunPython(update_scraper_id, reverse_code=revert_scraper_id),
    ]
