# Generated by Django 5.2.4 on 2025-09-01 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0008_update_google_scraper_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nome Template"),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("single", "Analisi Singola"),
                            ("comparative", "Analisi Comparativa"),
                        ],
                        default="single",
                        max_length=20,
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        default=dict, help_text="Filtri di selezione per il report."
                    ),
                ),
                (
                    "widgets",
                    models.JSONField(
                        default=list,
                        help_text="Widget di contenuto da includere nel report.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Template di Report",
                "verbose_name_plural": "Template di Report",
                "ordering": ["user", "-updated_at"],
            },
        ),
    ]
