# Generated by Django 5.2.4 on 2025-09-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0009_reporttemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="original_url",
            field=models.URLField(
                blank=True,
                help_text="Direct link to the original review",
                max_length=1024,
                null=True,
            ),
        ),
    ]
