# Generated by Django 5.2.4 on 2025-09-11 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        ("resort", "0005_resort_company"),
        ("reviews", "0010_review_original_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledScraping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Un nome per questa attività di scraping, es. 'Scraping Giornaliero Google'",
                        max_length=200,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Disattiva per sospendere questa attività programmata.",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Ogni Giorno"),
                            ("weekly", "Ogni Settimana"),
                        ],
                        default="daily",
                        max_length=10,
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Lunedì"),
                            ("2", "Martedì"),
                            ("3", "Mercoledì"),
                            ("4", "Giovedì"),
                            ("5", "Venerdì"),
                            ("6", "Sabato"),
                            ("0", "Domenica"),
                        ],
                        default="1",
                        max_length=1,
                    ),
                ),
                ("hour", models.IntegerField(default=2)),
                ("minute", models.IntegerField(default=0)),
                (
                    "scrape_period_days",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Recupera solo le recensioni degli ultimi X giorni. Lascia 0 per recuperarle tutte.",
                    ),
                ),
                (
                    "max_reviews_booking",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Numero massimo di recensioni da recuperare da Booking.com.",
                    ),
                ),
                (
                    "max_reviews_google",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Numero massimo di recensioni da recuperare da Google.",
                    ),
                ),
                (
                    "max_reviews_tripadvisor",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Numero massimo di recensioni da recuperare da Tripadvisor.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "periodic_task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_celery_beat.periodictask",
                    ),
                ),
                (
                    "resorts",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Seleziona i resort specifici. Se lasciato vuoto, li include tutti.",
                        to="resort.resort",
                    ),
                ),
                (
                    "sources",
                    models.ManyToManyField(
                        help_text="Seleziona le fonti da scansionare.",
                        to="reviews.reviewsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scraping Programmato",
                "verbose_name_plural": "Scraping Programmati",
                "ordering": ["name"],
            },
        ),
    ]
