# Generated by Django 5.2.4 on 2026-04-13 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resort", "0006_seed_resorts"),
        ("reviews", "0011_scheduledscraping"),
    ]

    operations = [
        migrations.CreateModel(
            name="VeratourReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_guests",
                    models.PositiveIntegerField(help_text="Totale persone / Ospiti"),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="veratour_reports",
                        to="resort.resort",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Veratour",
                "verbose_name_plural": "Report Veratour",
                "ordering": ["-start_date"],
                "unique_together": {("resort", "start_date", "end_date")},
            },
        ),
    ]
