# Generated by Django 5.2.4 on 2026-04-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0012_veratourreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="veratourreport",
            name="data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="veratourreport",
            name="max_capacity",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Capienza Massima Struttura (inserita manualmente)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="veratourreport",
            name="total_guests",
            field=models.PositiveIntegerField(
                help_text="Totale persone / Ospiti (Schede Elaborate)"
            ),
        ),
    ]
