# Generated by Django 5.2.4 on 2026-04-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0013_veratourreport_data_veratourreport_max_capacity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewanalysis",
            name="is_anomaly",
            field=models.BooleanField(
                default=False,
                help_text="True if the numeric rating is very high but the sentiment is very negative.",
            ),
        ),
    ]
