# Generated by Django 5.2.4 on 2026-03-01 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_cards", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("company_name", models.CharField(blank=True, max_length=150)),
                ("primary_color", models.CharField(default="#111111", max_length=16)),
                ("secondary_color", models.CharField(default="#ffffff", max_length=16)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProfileCardSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton_key",
                    models.CharField(default="default", max_length=32, unique=True),
                ),
                ("default_token_days", models.PositiveSmallIntegerField(default=90)),
                ("require_phone", models.BooleanField(default=False)),
                ("require_department", models.BooleanField(default=False)),
                ("auto_update_wallet_passes", models.BooleanField(default=False)),
                ("enable_multi_brand_templates", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="profilecard",
            name="department",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="profilecard",
            name="phone",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="profilecard",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cards",
                to="profile_cards.cardtemplate",
            ),
        ),
    ]
