# Generated by Django 5.2.4 on 2026-03-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_cards", "0002_cardtemplate_profilecardsettings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardtemplate",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="profilecard",
            name="applied_template_version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
