# Generated by Django 5.2.4 on 2026-03-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_cards", "0003_cardtemplate_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilecard",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="profilecard",
            name="website_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="profilecard",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
