# Generated by Django 5.2.4 on 2026-03-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profile_cards",
            "0004_profilecard_linkedin_url_profilecard_website_url_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profilecard",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_cards/avatars/"
            ),
        ),
    ]
