# Generated by Django 5.2.4 on 2026-03-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_cards", "0005_profilecard_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilecardsettings",
            name="show_apple_wallet",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profilecardsettings",
            name="show_google_wallet",
            field=models.BooleanField(default=True),
        ),
    ]
