# Generated by Django 5.2.4 on 2026-03-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_cards", "0006_profilecardsettings_show_apple_wallet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardtemplate",
            name="border_radius",
            field=models.CharField(default="12px", max_length=16),
        ),
        migrations.AddField(
            model_name="cardtemplate",
            name="button_style",
            field=models.CharField(
                choices=[
                    ("filled", "Filled"),
                    ("outline", "Outline"),
                    ("soft", "Soft / Glass"),
                ],
                default="filled",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cardtemplate",
            name="font_family",
            field=models.CharField(
                choices=[
                    ("Inter", "Inter (Modern)"),
                    ("Roboto", "Roboto (Standard)"),
                    ("Montserrat", "Montserrat (Elegant)"),
                    ("Playfair Display", "Playfair (Classic)"),
                ],
                default="Inter",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="profilecard",
            name="show_apple_wallet",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profilecard",
            name="show_google_wallet",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profilecard",
            name="show_linkedin",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profilecard",
            name="show_website",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profilecard",
            name="show_whatsapp",
            field=models.BooleanField(default=True),
        ),
    ]
