# Generated by Django 5.2.4 on 2026-03-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profile_cards",
            "0007_cardtemplate_border_radius_cardtemplate_button_style_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cardtemplate",
            name="header_gradient_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cardtemplate",
            name="header_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_cards/headers/"
            ),
        ),
        migrations.AddField(
            model_name="profilecard",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
