# Generated by Django 5.2.4 on 2026-03-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_cards", "0008_cardtemplate_header_gradient_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardtemplate",
            name="background_pattern",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("grain", "Film Grain"),
                    ("mesh", "Soft Mesh"),
                    ("silk", "Luxury Silk Texture"),
                ],
                default="none",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="cardtemplate",
            name="layout_type",
            field=models.CharField(
                choices=[
                    ("executive", "Executive (Professional Focus)"),
                    ("creative", "Creative (Visual/Social Focus)"),
                    ("minimal", "Minimalist (Pure Typography)"),
                ],
                default="executive",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="profilecard",
            name="cta_text",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="profilecard",
            name="cta_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="profilecard",
            name="enable_lead_capture",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profilecard",
            name="skills",
            field=models.CharField(
                blank=True, help_text="Comma separated skills", max_length=255
            ),
        ),
    ]
