# Generated by Django 5.2.4 on 2025-11-26 14:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VerifiedDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "In attesa"),
                            ("VERIFIED", "Verificato"),
                            ("NEEDS_REVIEW", "Richiede revisione manuale"),
                            ("FAILED", "Verifica fallita"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "document_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "issuer_country",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                ("raw_ocr_response", models.JSONField(default=dict)),
                ("confidence_scores", models.JSONField(default=dict)),
                ("review_notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Documento Verificato",
                "verbose_name_plural": "Documenti Verificati",
                "ordering": ["-created_at"],
            },
        ),
    ]
