# Generated by Django 5.2.4 on 2025-11-04 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0003_company_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LayoutTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_layout",
                    models.CharField(
                        help_text="Nome del layout (es. 'Layout Estivo', 'Menu Serale').",
                        max_length=100,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logo da visualizzare sul menu.",
                        null=True,
                        upload_to="menu_logos/",
                    ),
                ),
                (
                    "font_principale",
                    models.CharField(
                        default="Helvetica",
                        help_text="Nome del font da utilizzare per i titoli.",
                        max_length=100,
                    ),
                ),
                (
                    "colore_font",
                    models.CharField(
                        default="#000000",
                        help_text="Colore del testo in formato esadecimale (es. #RRGGBB).",
                        max_length=7,
                    ),
                ),
                ("data_creazione", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layout_templates",
                        to="clients.company",
                    ),
                ),
                (
                    "creato_da",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="layout_templates_creati",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Layout Template",
                "verbose_name_plural": "Layout Templates",
            },
        ),
        migrations.CreateModel(
            name="Piatto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(help_text="Il nome del piatto.", max_length=200),
                ),
                (
                    "descrizione",
                    models.TextField(
                        blank=True,
                        help_text="Una breve descrizione del piatto e dei suoi ingredienti.",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("antipasto", "Antipasto"),
                            ("primo", "Primo"),
                            ("secondo", "Secondo"),
                            ("contorno", "Contorno"),
                            ("dessert", "Dessert"),
                            ("bevanda", "Bevanda"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "allergeni",
                    models.CharField(
                        blank=True,
                        help_text="Elenco degli allergeni presenti, separati da virgola.",
                        max_length=255,
                    ),
                ),
                (
                    "prezzo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Prezzo del piatto.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="L'azienda a cui questo piatto appartiene.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="piatti",
                        to="clients.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Piatto",
                "verbose_name_plural": "Piatti",
                "ordering": ["categoria", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome del menu (es. 'Menu Pranzo 15/07/2024').",
                        max_length=200,
                    ),
                ),
                ("data_creazione", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu",
                        to="clients.company",
                    ),
                ),
                (
                    "creato_da",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="menu_creati",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "layout",
                    models.ForeignKey(
                        blank=True,
                        help_text="Il layout da applicare a questo menu.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="menu_generator.layouttemplate",
                    ),
                ),
                (
                    "piatti",
                    models.ManyToManyField(
                        help_text="Piatti inclusi in questo menu.",
                        related_name="menu",
                        to="menu_generator.piatto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu",
                "verbose_name_plural": "Menu",
                "ordering": ["-data_creazione"],
            },
        ),
    ]
