# Generated by Django 5.2.4 on 2025-11-04 09:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_structure_structurerole_structuremembership"),
        ("menu_generator", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="layouttemplate",
            name="background_image",
            field=models.ImageField(
                blank=True,
                help_text="Immagine di sfondo opzionale.",
                null=True,
                upload_to="menu_layouts/backgrounds/",
            ),
        ),
        migrations.AddField(
            model_name="layouttemplate",
            name="data_modifica",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="layouttemplate",
            name="documento_word",
            field=models.FileField(
                blank=True,
                help_text="Template Word riutilizzabile (.docx).",
                null=True,
                upload_to="menu_layouts/docx/",
            ),
        ),
        migrations.AddField(
            model_name="layouttemplate",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Metadati aggiuntivi per l'editor front-end.",
            ),
        ),
        migrations.AddField(
            model_name="layouttemplate",
            name="palette_colori",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Palette cromatica utilizzata nel layout (accenti, sfondi).",
            ),
        ),
        migrations.AddField(
            model_name="layouttemplate",
            name="struttura_blocchi",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Configurazione drag&drop dei blocchi del menu.",
            ),
        ),
        migrations.AddField(
            model_name="layouttemplate",
            name="versione",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="menu",
            name="data_evento",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Data in cui il menu verrà servito.",
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="data_modifica",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="menu",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="menu",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Metadati aggiuntivi per suggerimenti o AI.",
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="note",
            field=models.TextField(
                blank=True, help_text="Note aggiuntive da mostrare internamente."
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="ospiti_target",
            field=models.CharField(
                blank=True,
                help_text="Note sugli ospiti (es. VIP, congresso, matrimonio).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="menu",
            name="struttura",
            field=models.ForeignKey(
                blank=True,
                help_text="Struttura per cui è creato il menu.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="menu",
                to="clients.structure",
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="turno",
            field=models.CharField(
                choices=[
                    ("colazione", "Colazione"),
                    ("pranzo", "Pranzo"),
                    ("cena", "Cena"),
                    ("speciale", "Evento Speciale"),
                ],
                default="pranzo",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="piatto",
            name="allergen_summary",
            field=models.CharField(
                blank=True,
                help_text="Descrizione personalizzata degli allergeni da mostrare nel menu.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="piatto",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="piatto",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="piatto",
            name="note_internal",
            field=models.TextField(
                blank=True,
                help_text="Note interne per la brigata o per la pianificazione.",
            ),
        ),
        migrations.AddField(
            model_name="piatto",
            name="porzioni",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Numero di porzioni standard.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="piatto",
            name="stagionalita",
            field=models.CharField(
                choices=[
                    ("annuale", "Tutto l'anno"),
                    ("primavera", "Primavera"),
                    ("estate", "Estate"),
                    ("autunno", "Autunno"),
                    ("inverno", "Inverno"),
                ],
                default="annuale",
                help_text="Periodo di disponibilità suggerito per il piatto.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="piatto",
            name="tempo_cottura_minuti",
            field=models.PositiveIntegerField(
                default=0, help_text="Tempo di cottura stimato (minuti)."
            ),
        ),
        migrations.AddField(
            model_name="piatto",
            name="tempo_preparazione_minuti",
            field=models.PositiveIntegerField(
                default=0, help_text="Tempo di preparazione stimato (minuti)."
            ),
        ),
        migrations.AddField(
            model_name="piatto",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="piatto",
            name="variante_di",
            field=models.ForeignKey(
                blank=True,
                help_text="Permette di collegare piatti alternativi (es. versione vegan).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="varianti",
                to="menu_generator.piatto",
            ),
        ),
        migrations.RemoveField(
            model_name="piatto",
            name="allergeni",
        ),
        migrations.AlterField(
            model_name="piatto",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("antipasto", "Antipasto"),
                    ("primo", "Primo"),
                    ("secondo", "Secondo"),
                    ("contorno", "Contorno"),
                    ("dessert", "Dessert"),
                    ("bevanda", "Bevanda"),
                    ("altro", "Altro"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="piatto",
            name="descrizione",
            field=models.TextField(
                blank=True, help_text="Descrizione del piatto e note sugli ingredienti."
            ),
        ),
        migrations.AlterField(
            model_name="piatto",
            name="prezzo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Prezzo del piatto.",
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="layouttemplate",
            unique_together={("company", "nome_layout", "versione")},
        ),
        migrations.CreateModel(
            name="Allergene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codice",
                    models.SlugField(
                        help_text="Codice univoco (es. glutine, latte).", unique=True
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome visualizzato dell'allergene.", max_length=150
                    ),
                ),
                ("descrizione", models.TextField(blank=True)),
                (
                    "icona_svg",
                    models.TextField(
                        blank=True,
                        help_text="Markup SVG opzionale da mostrare sui documenti.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Società proprietaria (lasciare vuoto per allergeni globali).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allergeni_personalizzati",
                        to="clients.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allergene",
                "verbose_name_plural": "Allergeni",
                "ordering": ["codice"],
            },
        ),
        migrations.CreateModel(
            name="BaseFoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descrizione", models.TextField(blank=True)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("antipasto", "Antipasto"),
                            ("primo", "Primo"),
                            ("secondo", "Secondo"),
                            ("contorno", "Contorno"),
                            ("dessert", "Dessert"),
                            ("bevanda", "Bevanda"),
                            ("altro", "Altro"),
                        ],
                        default="altro",
                        max_length=50,
                    ),
                ),
                (
                    "informazioni_nutrizionali",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Valori nutrizionali standard.",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "versione",
                    models.PositiveIntegerField(
                        default=1, help_text="Versione attuale dell'alimento base."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allergeni_default",
                    models.ManyToManyField(
                        blank=True,
                        related_name="alimenti_default",
                        to="menu_generator.allergene",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alimenti_base",
                        to="clients.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alimento Base",
                "verbose_name_plural": "Alimenti Base",
            },
        ),
        migrations.AddField(
            model_name="piatto",
            name="base_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Voce di catalogo di riferimento per il piatto.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="piatti_associati",
                to="menu_generator.basefooditem",
            ),
        ),
        migrations.CreateModel(
            name="CavaliereTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                (
                    "configurazione",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Posizionamento testi, logo, colori, dimensioni.",
                    ),
                ),
                (
                    "documento_word",
                    models.FileField(
                        blank=True,
                        help_text="Template Word specifico per i cavalieri.",
                        null=True,
                        upload_to="cavalieri/docx/",
                    ),
                ),
                ("creato_il", models.DateTimeField(auto_now_add=True)),
                ("aggiornato_il", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cavalieri_templates",
                        to="clients.company",
                    ),
                ),
                (
                    "creato_da",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cavalieri_templates_creati",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "layout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cavalieri",
                        to="menu_generator.layouttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Cavaliere",
                "verbose_name_plural": "Template Cavalieri",
                "unique_together": {("company", "nome")},
            },
        ),
        migrations.AddField(
            model_name="menu",
            name="cavaliere_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template da utilizzare per i cavalieri generati.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="menu_generator.cavalieretemplate",
            ),
        ),
        migrations.CreateModel(
            name="Ingrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome dell'ingrediente.", max_length=200
                    ),
                ),
                ("descrizione", models.TextField(blank=True)),
                (
                    "stagionalita",
                    models.CharField(
                        choices=[
                            ("annuale", "Tutto l'anno"),
                            ("primavera", "Primavera"),
                            ("estate", "Estate"),
                            ("autunno", "Autunno"),
                            ("inverno", "Inverno"),
                        ],
                        default="annuale",
                        max_length=20,
                    ),
                ),
                (
                    "disponibilita",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Informazioni opzionali su disponibilità o fornitore.",
                    ),
                ),
                (
                    "informazioni_nutrizionali",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Valori nutrizionali (kcal, proteine, etc.).",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allergeni",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Allergeni contenuti nell'ingrediente.",
                        related_name="ingredienti",
                        to="menu_generator.allergene",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredienti",
                        to="clients.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingrediente",
                "verbose_name_plural": "Ingredienti",
                "ordering": ["nome"],
                "unique_together": {("company", "nome")},
            },
        ),
        migrations.AddField(
            model_name="basefooditem",
            name="ingredienti_default",
            field=models.ManyToManyField(
                blank=True,
                related_name="alimenti_default",
                to="menu_generator.ingrediente",
            ),
        ),
        migrations.AddField(
            model_name="piatto",
            name="ingredienti",
            field=models.ManyToManyField(
                blank=True,
                help_text="Lista ingredienti collegati al piatto.",
                related_name="piatti",
                to="menu_generator.ingrediente",
            ),
        ),
        migrations.CreateModel(
            name="MenuVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payload", models.JSONField(help_text="Snapshot completo del menu.")),
                ("creato_il", models.DateTimeField(auto_now_add=True)),
                (
                    "creato_da",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="menu_versioni_create",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versioni",
                        to="menu_generator.menu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Versione Menu",
                "verbose_name_plural": "Versioni Menu",
                "ordering": ["-creato_il"],
            },
        ),
        migrations.AddField(
            model_name="piatto",
            name="allergeni",
            field=models.ManyToManyField(
                blank=True,
                help_text="Allergeni derivati per il piatto.",
                related_name="piatti",
                to="menu_generator.allergene",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="basefooditem",
            unique_together={("company", "nome", "versione")},
        ),
    ]
