# Generated by Django 5.2.4 on 2025-11-18 09:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu_generator", "0002_layouttemplate_background_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuDocumentJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "output_format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("docx", "DOCX"), ("zip", "ZIP")],
                        default="pdf",
                        max_length=10,
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[("menu", "Menu"), ("cavaliere", "Cavaliere")],
                        default="menu",
                        max_length=20,
                    ),
                ),
                ("include_cavalieri", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "In attesa"),
                            ("running", "In esecuzione"),
                            ("success", "Completato"),
                            ("failed", "Errore"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress", models.PositiveIntegerField(default=0)),
                (
                    "result_file",
                    models.FileField(
                        blank=True, null=True, upload_to="menu_documents/"
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="menu_doc_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_jobs",
                        to="menu_generator.menu",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
