# Generated by Django 5.2.4 on 2026-03-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu_generator", "0005_layouttemplate_struttura"),
    ]

    operations = [
        migrations.AddField(
            model_name="piatto",
            name="immagine",
            field=models.ImageField(
                blank=True,
                help_text="Foto opzionale del piatto.",
                null=True,
                upload_to="menu_piatti/",
            ),
        ),
    ]
