# Generated by Django 5.2.4 on 2026-03-05 09:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu_generator", "0006_piatto_immagine"),
    ]

    operations = [
        migrations.AddField(
            model_name="layouttemplate",
            name="is_preset",
            field=models.BooleanField(
                default=False,
                help_text="Se vero, il layout è un preset di sistema non modificabile.",
            ),
        ),
        migrations.AddField(
            model_name="piatto",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
