# Generated by Django 5.2.4 on 2026-03-06 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economato", "0001_initial"),
        ("menu_generator", "0007_layouttemplate_is_preset_piatto_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingrediente",
            name="economato_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Collegamento all'articolo dell'economato per il calcolo dei costi.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_ingredients",
                to="economato.economatoitem",
            ),
        ),
        migrations.CreateModel(
            name="PiattoIngrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantita",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Quantità necessaria per la ricetta.",
                        max_digits=10,
                    ),
                ),
                (
                    "unita_misura",
                    models.CharField(
                        choices=[
                            ("g", "Grammi"),
                            ("kg", "Chilogrammi"),
                            ("ml", "Millilitri"),
                            ("lt", "Litri"),
                            ("pz", "Pezzi"),
                            ("qb", "Quanto basta"),
                        ],
                        default="g",
                        max_length=10,
                    ),
                ),
                (
                    "scarto_percentuale",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentuale di scarto (es. 20.00 per il 20%). Calcola il passaggio da peso lordo a peso netto.",
                        max_digits=5,
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Note specifiche per l'uso in questa ricetta.",
                        max_length=255,
                    ),
                ),
                (
                    "ingrediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utilizzi_nei_piatti",
                        to="menu_generator.ingrediente",
                    ),
                ),
                (
                    "piatto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="composizione_ingredienti",
                        to="menu_generator.piatto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingrediente in Ricetta",
                "verbose_name_plural": "Ingredienti in Ricetta",
                "unique_together": {("piatto", "ingrediente")},
            },
        ),
    ]
