# Generated by Django 5.2.4 on 2025-08-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("svago", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesession",
            name="board_state",
            field=models.CharField(
                default="[null, null, null, null, null, null, null, null, null]",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="gamesession",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "In attesa"),
                    ("active", "In corso"),
                    ("finished", "Terminata"),
                    ("draw", "Pareggio"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
