# Generated by Django 5.2.4 on 2025-09-26 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("resort", "0005_resort_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_engine_id",
                    models.CharField(
                        blank=True,
                        help_text="ID univoco dal booking engine esterno",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "guest_name",
                    models.CharField(
                        help_text="Nome del cliente principale", max_length=255
                    ),
                ),
                (
                    "guest_email",
                    models.EmailField(
                        help_text="Email del cliente principale", max_length=254
                    ),
                ),
                ("check_in_date", models.DateField(verbose_name="Data di Check-in")),
                ("check_out_date", models.DateField(verbose_name="Data di Check-out")),
                (
                    "room_details",
                    models.TextField(
                        blank=True, help_text="Dettagli sulla camera o altre note"
                    ),
                ),
                (
                    "access_token_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash del token di accesso per il link 'magico'",
                        max_length=128,
                    ),
                ),
                (
                    "access_token_expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Data di scadenza del token", null=True
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp del blocco per tentativi di brute force",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "In attesa di check-in"),
                            ("completed", "Check-in Completato"),
                            ("verified", "Verificato dallo Staff"),
                            ("archived", "Archiviato"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "pms_payload_snapshot",
                    models.JSONField(
                        blank=True,
                        help_text="Snapshot dei dati originali dal booking engine",
                        null=True,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Per futura gestione multi-proprietà",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="resort.resort",
                    ),
                ),
            ],
            options={
                "ordering": ["-check_in_date"],
            },
        ),
        migrations.CreateModel(
            name="CheckInProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("created", "Creato"),
                            ("in_progress", "In Corso"),
                            ("signed", "Firmato"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "signed_pdf_url",
                    models.URLField(
                        blank=True,
                        help_text="URL al PDF di riepilogo firmato",
                        null=True,
                    ),
                ),
                (
                    "signature_meta",
                    models.JSONField(
                        blank=True,
                        help_text="Metadati della firma (IP, UA, hash del doc)",
                        null=True,
                    ),
                ),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkin_process",
                        to="bookings.booking",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guests",
                        to="bookings.booking",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuestDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "storage_url",
                    models.URLField(
                        help_text="URL del file cifrato su storage esterno (es. S3)",
                        max_length=512,
                    ),
                ),
                (
                    "sha256_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash del file per verificarne l'integrità",
                        max_length=64,
                    ),
                ),
                (
                    "scanned_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp della scansione antivirus/OCR",
                        null=True,
                    ),
                ),
                (
                    "scan_result",
                    models.JSONField(
                        blank=True,
                        help_text="Risultato della scansione e dell'OCR",
                        null=True,
                    ),
                ),
                (
                    "ocr_confidence",
                    models.FloatField(
                        blank=True,
                        help_text="Punteggio di confidenza dell'estrazione OCR",
                        null=True,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guest",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document",
                        to="bookings.guest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Consent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("terms_v1", "Termini e Condizioni v1.0"),
                            ("privacy_v1", "Informativa Privacy v1.0"),
                            ("marketing_newsletter", "Iscrizione Newsletter"),
                        ],
                        max_length=50,
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "policy_version",
                    models.CharField(
                        help_text="Es. 'v1.2 del 2024-09-26'", max_length=20
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Origine del consenso (es. web_checkin, email)",
                        max_length=50,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "unique_together": {("booking", "type")},
            },
        ),
    ]
