# Generated by Django 5.2.4 on 2025-09-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkinprocess",
            name="otp_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="checkinprocess",
            name="otp_code_hash",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="checkinprocess",
            name="otp_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="checkinprocess",
            name="state",
            field=models.CharField(
                choices=[
                    ("awaiting_data", "In attesa di dati"),
                    ("awaiting_otp", "In attesa di OTP"),
                    ("completed", "Completato"),
                ],
                default="awaiting_data",
                max_length=20,
            ),
        ),
    ]
