# Generated by Django 5.2.4 on 2025-09-26 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_checkinprocess_otp_attempts_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "ordering": ["-check_in_date"],
                "permissions": [("can_export_bookings", "Can export booking data")],
            },
        ),
        migrations.AlterModelOptions(
            name="guestdocument",
            options={
                "permissions": [("can_verify_document", "Can verify guest document")]
            },
        ),
    ]
