# Generated by Django 5.2.4 on 2025-09-26 14:52

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_auditlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guestdocument",
            name="storage_url",
        ),
        migrations.AddField(
            model_name="guestdocument",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="File del documento d'identità",
                null=True,
                upload_to="guest_documents/%Y/%m/%d/",
            ),
        ),
        migrations.AlterField(
            model_name="checkinprocess",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("awaiting_data", "In attesa di dati"),
                    ("awaiting_otp", "In attesa di OTP"),
                    ("signed", "Firmato"),
                    ("needs_review", "Da Revisionare"),
                    ("completed", "Completato"),
                ],
                default="awaiting_data",
                max_length=50,
                protected=True,
            ),
        ),
        migrations.AlterField(
            model_name="guestdocument",
            name="scan_result",
            field=models.CharField(
                blank=True,
                help_text="Risultato della scansione (es. 'clean', 'infected')",
                max_length=20,
                null=True,
            ),
        ),
    ]
