# Generated by Django 5.2.4 on 2025-11-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookings",
            "0005_remove_guestdocument_storage_url_guestdocument_file_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="access_token_revoked",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Flag di revoca esplicita del token",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="access_token_revoked_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp della revoca del token", null=True
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="access_token_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hash del token di accesso per il link 'magico'",
                max_length=128,
            ),
        ),
    ]
