# Generated by Django 5.2.4 on 2025-11-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_checkintransitionevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="access_token_signature",
            field=models.TextField(
                blank=True, help_text="Token codificato per riuso controllato"
            ),
        ),
    ]
