# Generated by Django 5.2.4 on 2025-11-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_booking_access_token_signature"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkinprocess",
            name="pdf_status",
            field=models.CharField(
                choices=[
                    ("pending", "In coda"),
                    ("processing", "In elaborazione"),
                    ("ready", "Pronto"),
                    ("failed", "Errore"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="checkinprocess",
            name="qr_code_path",
            field=models.CharField(
                blank=True,
                help_text="Percorso interno del QR code",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="checkinprocess",
            name="qr_code_url",
            field=models.URLField(
                blank=True, help_text="URL firmato del QR code", null=True
            ),
        ),
        migrations.AddField(
            model_name="checkinprocess",
            name="qr_status",
            field=models.CharField(
                choices=[
                    ("pending", "In coda"),
                    ("processing", "In elaborazione"),
                    ("ready", "Pronto"),
                    ("failed", "Errore"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="checkinprocess",
            name="signed_pdf_checksum",
            field=models.CharField(
                blank=True,
                help_text="Hash SHA256 del PDF firmato",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="checkinprocess",
            name="signed_pdf_path",
            field=models.CharField(
                blank=True,
                help_text="Percorso interno del PDF firmato",
                max_length=512,
                null=True,
            ),
        ),
    ]
