# Generated by Django 5.2.4 on 2025-11-26 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0009_checkinprocess_pdf_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkinprocess",
            name="otp_last_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkinprocess",
            name="otp_locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="OTPAttemptLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("was_successful", models.BooleanField(default=False)),
                ("reason", models.CharField(max_length=50)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "attempts_remaining",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_attempts_log",
                        to="bookings.booking",
                    ),
                ),
                (
                    "checkin_process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_attempts_log",
                        to="bookings.checkinprocess",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
