# Generated by Django 5.2.4 on 2025-11-26 09:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0010_checkinprocess_otp_last_sent_at_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="consent",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="consent",
            name="accepted_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Timestamp di accettazione della policy",
            ),
        ),
        migrations.AddField(
            model_name="consent",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consent",
            name="status",
            field=models.CharField(
                choices=[("current", "Current"), ("superseded", "Superseded")],
                db_index=True,
                default="current",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="consent",
            name="superseded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consent",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="consent",
            name="policy_version",
            field=models.CharField(
                help_text="Es. 'v1.2 del 2024-09-26'", max_length=50
            ),
        ),
        migrations.AddConstraint(
            model_name="consent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "current")),
                fields=("booking", "type"),
                name="unique_current_consent_per_type",
            ),
        ),
    ]
