# Generated by Django 5.2.4 on 2025-11-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0011_alter_consent_unique_together_consent_accepted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="document_expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="guest",
            name="document_number",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
