# Generated by Django 5.2.4 on 2025-08-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_tickethistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="image",
        ),
        migrations.AddField(
            model_name="ticket",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="ticket_attachments/"
            ),
        ),
    ]
