# Generated by Django 5.2.4 on 2025-08-18 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resort", "0003_add_room_model"),
        ("tickets", "0004_update_ticket_attachment_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="resort.room",
            ),
        ),
    ]
