# Generated by Django 5.2.4 on 2025-08-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0005_add_room_to_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Bassa"),
                    ("medium", "Media"),
                    ("high", "Alta"),
                    ("urgent", "Urgente"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
    ]
