# Generated by Django 5.2.4 on 2025-08-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0006_add_priority_to_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Bassa"),
                    ("medium", "Media"),
                    ("high", "Alta"),
                    ("urgent", "Urgente"),
                ],
                db_index=True,
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Aperto"),
                    ("in_progress", "In lavorazione"),
                    ("resolved", "Risolto"),
                    ("closed", "Chiuso"),
                ],
                db_index=True,
                default="open",
                max_length=20,
            ),
        ),
    ]
