# Generated by Django 5.2.4 on 2025-08-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0007_add_indexes_to_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketcomment",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="comment_attachments/"
            ),
        ),
        migrations.AlterField(
            model_name="ticketcomment",
            name="comment",
            field=models.TextField(blank=True),
        ),
    ]
