# Generated by Django 5.2.4 on 2025-09-16 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0001_initial"),
        ("tickets", "0008_ticketcomment_attachment_alter_ticketcomment_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="required_skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="skills.skill",
                verbose_name="Competenza Richiesta",
            ),
        ),
    ]
