# Generated by Django 5.2.4 on 2025-09-16 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resort", "0005_resort_company"),
        ("tickets", "0009_ticket_required_skill"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProactiveMaintenanceAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Motivo dell'allerta, es. '3 ticket in 30 giorni'."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_addressed",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Gestita"
                    ),
                ),
                (
                    "last_ticket",
                    models.ForeignKey(
                        help_text="L'ultimo ticket che ha generato l'allerta.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tickets.ticket",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proactive_alerts",
                        to="resort.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allerta Manutenzione Proattiva",
                "verbose_name_plural": "Allerte Manutenzione Proattiva",
                "ordering": ["-created_at"],
            },
        ),
    ]
