# Generated by Django 5.2.4 on 2025-09-16 08:47

from django.db import migrations

def create_scheduled_task(apps, schema_editor):
    CrontabSchedule = apps.get_model('django_celery_beat', 'CrontabSchedule')
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')

    # Create a crontab schedule to run daily at 2 AM
    schedule, _ = CrontabSchedule.objects.get_or_create(
        minute='0',
        hour='2',
        day_of_week='*',
        day_of_month='*',
        month_of_year='*',
    )

    # Create the periodic task
    PeriodicTask.objects.get_or_create(
        crontab=schedule,
        name='Analisi pattern ticket per manutenzione proattiva',
        task='tickets.tasks.analyze_ticket_patterns',
        defaults={'enabled': True},
    )

def remove_scheduled_task(apps, schema_editor):
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    PeriodicTask.objects.filter(
        name='Analisi pattern ticket per manutenzione proattiva'
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0010_proactivemaintenancealert"),
        ('django_celery_beat', '0001_initial'), # Dependency to ensure models exist
    ]

    operations = [
        migrations.RunPython(create_scheduled_task, reverse_code=remove_scheduled_task),
    ]
