# Generated by Django 5.2.4 on 2025-09-16 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resort", "0005_resort_company"),
        ("tickets", "0011_schedule_proactive_analysis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proactivemaintenancealert",
            name="room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proactive_alerts",
                to="resort.room",
            ),
        ),
    ]
