# Generated by Django 5.2.4 on 2025-09-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0012_alter_proactivemaintenancealert_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="due_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data di Scadenza"
            ),
        ),
    ]
