# Generated by Django 5.2.4 on 2025-10-27 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0013_ticket_due_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="completion_photo",
            field=models.ImageField(
                blank=True,
                help_text="Foto del lavoro completato obbligatoria per la chiusura.",
                null=True,
                upload_to="ticket_completion_photos/",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="deadline_reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp dell'ultimo promemoria inviato per la scadenza.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="TicketDeadlineChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_due_date", models.DateTimeField(blank=True, null=True)),
                ("new_due_date", models.DateTimeField(blank=True, null=True)),
                ("justification", models.TextField(blank=True)),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("set", "Impostazione iniziale"),
                            ("extend", "Proroga"),
                            ("shorten", "Anticipo"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deadline_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deadline_changes",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
