# Generated by Django 5.2.4 on 2025-11-03 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0015_ticket_budget_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="acknowledged_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data conferma scadenza"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acknowledged_tickets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Scadenza confermata da",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="acknowledged_due_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Scadenza confermata dal manutentore incaricato.",
                null=True,
                verbose_name="Scadenza confermata",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="initial_due_date",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Scadenza comunicata da chi ha aperto il ticket.",
                null=True,
                verbose_name="Scadenza iniziale",
            ),
        ),
    ]
