# Generated by Django 5.2.4 on 2025-11-03 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0016_ticket_acknowledged_at_ticket_acknowledged_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="claimed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data presa in carico"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="claimed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claimed_tickets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Presa in carico da",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="first_claimed_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Prima volta in cui un manutentore ha preso in carico il ticket.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="last_released_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Ultima volta in cui il ticket è tornato non assegnato.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="unassigned_notification_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp dell'ultimo broadcast per ticket non assegnato.",
                null=True,
            ),
        ),
    ]
