# Generated by Django 5.2.4 on 2025-08-25 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IT_Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Titolo breve e descrittivo del problema IT.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Descrizione dettagliata del problema."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Aperto"),
                            ("in_progress", "In Lavorazione"),
                            ("resolved", "Risolto"),
                            ("closed", "Chiuso"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Bassa"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                            ("urgent", "Urgente"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("pc", "PC/Laptop"),
                            ("printer", "Stampante"),
                            ("network", "Rete/Wi-Fi"),
                            ("software", "Software/Applicativo"),
                            ("other", "Altro"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Tipo di Dispositivo",
                    ),
                ),
                (
                    "anydesk_id",
                    models.CharField(
                        blank=True,
                        help_text="Se pertinente, inserire l'ID AnyDesk per l'assistenza remota.",
                        max_length=50,
                        verbose_name="ID AnyDesk",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Allega screenshot o file di log.",
                        null=True,
                        upload_to="it_ticket_attachments/",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_it_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="it_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket IT",
                "verbose_name_plural": "Tickets IT",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="it_support__status_9ba10f_idx"
                    ),
                    models.Index(
                        fields=["priority"], name="it_support__priorit_19d073_idx"
                    ),
                    models.Index(
                        fields=["user"], name="it_support__user_id_bb08e9_idx"
                    ),
                ],
            },
        ),
    ]
