# Generated by Django 5.2.4 on 2025-08-25 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("it_support", "0002_it_ticketcomment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="it_ticket",
            name="chat_status",
            field=models.CharField(
                choices=[
                    ("none", "Nessuna Richiesta"),
                    ("requested", "Richiesta in Attesa"),
                    ("active", "Attiva"),
                    ("declined", "Rifiutata"),
                    ("ended", "Terminata"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="it_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="it_support.it_ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Messaggio Chat IT",
                "verbose_name_plural": "Messaggi Chat IT",
                "ordering": ["timestamp"],
            },
        ),
    ]
