# Generated by Django 5.2.4 on 2025-08-25 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
        ("it_support", "0004_alter_chatmessage_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="it_ticket",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="it_tickets",
                to="assets.asset",
                verbose_name="Asset Correlato",
            ),
        ),
    ]
