# Generated by Django 5.2.4 on 2025-08-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("it_support", "0005_it_ticket_asset"),
    ]

    operations = [
        migrations.AddField(
            model_name="it_ticket",
            name="intervention_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Costo Intervento",
            ),
        ),
    ]
