# Generated by Django 5.2.4 on 2025-08-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("it_support", "0006_it_ticket_intervention_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="it_chat_attachments/"
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="message",
            field=models.TextField(blank=True),
        ),
    ]
