# Generated by Django 5.2.4 on 2025-10-23 22:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_company_logo"),
        ("notifications", "0002_add_indexes_to_notification"),
        ("resort", "0006_seed_resorts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("endpoint", models.URLField(unique=True)),
                ("p256dh", models.CharField(max_length=255)),
                ("auth", models.CharField(max_length=255)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("web", "Web"),
                            ("android", "Android"),
                            ("ios", "iOS"),
                        ],
                        default="web",
                        max_length=20,
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-is_pinned", "-created_at"]},
        ),
        migrations.AddField(
            model_name="notification",
            name="audience_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="clients.company",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="audience_resort",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="resort.resort",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="audience_roles",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista di ruoli destinatari se la notifica è condivisa.",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="body",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "Generale"),
                    ("task", "Attività"),
                    ("alert", "Avviso"),
                    ("system", "Sistema"),
                ],
                db_index=True,
                default="general",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="cta_label",
            field=models.CharField(blank=True, default="Apri", max_length=60),
        ),
        migrations.AddField(
            model_name="notification",
            name="delivery_channels",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Canali di consegna utilizzati (es. ['in_app', 'push']).",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="icon",
            field=models.CharField(blank=True, default="fa-bell", max_length=50),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_pinned",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="notification",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Bassa"),
                    ("normal", "Normale"),
                    ("high", "Alta"),
                    ("urgent", "Urgente"),
                ],
                db_index=True,
                default="normal",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="requires_acknowledgement",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="source",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="notification",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="link",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["category", "is_read"], name="notificatio_categor_2b809e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["priority", "is_read"], name="notificatio_priorit_60753b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["created_at"], name="notificatio_created_46ad24_idx"
            ),
        ),
        migrations.AddField(
            model_name="pushsubscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="push_subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="pushsubscription",
            index=models.Index(
                fields=["user", "is_active"], name="notificatio_user_id_1159a5_idx"
            ),
        ),
    ]
