# Generated by Django 5.2.4 on 2025-08-29 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("resort", "0005_resort_company"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nome Fornitore"),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Persona di Contatto",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Numero di Telefono",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Indirizzo"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Fornitore",
                "verbose_name_plural": "Fornitori",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Bozza"),
                            ("submitted", "Inviato"),
                            ("approved", "Approvato"),
                            ("completed", "Completato"),
                            ("cancelled", "Annullato"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Stato",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data Creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ultima Modifica"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_orders_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creato da",
                    ),
                ),
                (
                    "resort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_orders",
                        to="resort.resort",
                        verbose_name="Resort",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="purchase_orders.supplier",
                        verbose_name="Fornitore",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buono d'Ordine",
                "verbose_name_plural": "Buoni d'Ordine",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=255, verbose_name="Nome Prodotto"),
                ),
                (
                    "product_code",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Codice Prodotto",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantità")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prezzo Unitario"
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchase_orders.purchaseorder",
                        verbose_name="Buono d'Ordine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Articolo Buono d'Ordine",
                "verbose_name_plural": "Articoli Buoni d'Ordine",
            },
        ),
    ]
