# Generated by Django 5.2.4 on 2025-09-11 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_company_logo"),
        ("purchase_orders", "0002_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suppliers",
                to="clients.company",
                verbose_name="Società di Appartenenza",
            ),
        ),
    ]
