# Generated by Django 5.2.4 on 2025-09-16 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_orders", "0003_supplier_company"),
        ("resort", "0005_resort_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Categoria di Acquisto",
                "verbose_name_plural": "Categorie di Acquisto",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="budget",
            options={
                "ordering": ["-year", "-month", "resort", "category"],
                "verbose_name": "Budget",
                "verbose_name_plural": "Budget",
            },
        ),
        migrations.AlterUniqueTogether(
            name="budget",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="budget",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budgets",
                to="purchase_orders.purchasecategory",
                verbose_name="Categoria",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="purchase_orders.purchasecategory",
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="budget",
            unique_together={("resort", "year", "month", "category")},
        ),
    ]
